@startuml lab1
skinparam actorStyle awesome
Actor "Пользователь" as user
Actor "Администратор" as admin
Actor "Редактор" as editor
Actor "Комментатор" as commentor
Actor "Модератор" as moder

admin -|> user
editor -|> user
commentor -|> user
moder -|> user
user--  "Просматривать новости"
commentor --  "Редактировать свой комментарий"
admin --  "Редактировать чужой комментарий"
admin --  "Создать категорию"
admin --  "Удалить категорию"
admin --  "Удалить чужую публикацию"
admin --  "Изменить права пользователя"
admin --  "Запретить публикацию"
admin --  "Удалить чужой комментарий"
admin --  "Редактировать чужую публикацию"
admin --  "Переместить публикацию в\из категории"
moder --  "Редактировать чужой комментарий"

moder --  "Редактировать чужой комментарий"
moder --  "Запретить публикацию"
moder --  "Удалить чужой комментарий"
moder --  "Редактировать чужую публикацию"
moder --  "Переместить публикацию в\из категории"
moder --  "Создать комментарий"

commentor --  "Создать комментарий"
commentor --  "Удалить свой комментарий"

editor -- "Переместить публикацию в\из категории"
editor --  "Создать публикацию"
editor --  "Удалить свою публикацию"
editor --  "Редактировать свою публикацию"
@enduml