@startuml use_case
skinparam actorStyle awesome
left to right direction
actor Пользователь as User
actor Обучающийся as Student
actor Преподаватель as Teacher
actor Администратор as Admin
User <|- Student
User <|- Teacher
User <|- Admin

rectangle "Образовательная платформа с онлайн-курсами" as Platform {
  together{
    usecase "Регистрация"
    usecase "Авторизация"
    usecase "Редактирование данных своего профиля"
    usecase "Просмотр открытых курсов"
    usecase "Общение с пользователями через чат"
  }
  together{
    usecase "Просмотр доступных курсов"
    usecase "Просмотр своих оценок"
  }
  usecase "Просмотр\создание\удаление\изменение\n курса"
  usecase "Изменение\просмотр оценок проходящих курс обучающихся"
  usecase "Просмотр оценок обучающихся"
  usecase "Настройка доступа пользователей"
  usecase "Настройка доступа пользователей к своим курсам"
  usecase "Редактирование данных чужого профиля"
  usecase "Удаление чужих сообщений в чатах"
  usecase "Написание своих сообщений"
  usecase "Редактирование своих сообщений"
  usecase "Удаление своих сообщений"
  usecase "Создание чатов"
  usecase "Удаление созданных чатов"
  usecase "Редактирование созданных чатов"
  usecase "Ввод персональных данных"
  usecase "Ввод электронной почты"
  usecase "Ввод пароля"
}

"Общение с пользователями через чат" -- "Удаление созданных чатов": <<extend>>
"Общение с пользователями через чат" -- "Редактирование своих сообщений": <<extend>>
"Общение с пользователями через чат" -- "Редактирование созданных чатов": <<extend>>
"Общение с пользователями через чат" -- "Написание своих сообщений": <<extend>>
"Общение с пользователями через чат" -- "Удаление своих сообщений": <<extend>>
"Общение с пользователями через чат" -- "Создание чатов": <<extend>>

"Регистрация" -- "Ввод персональных данных": <<include>>
"Регистрация" -- "Ввод электронной почты": <<include>>
"Регистрация" -- "Ввод пароля": <<include>>

User -- "Регистрация"
User -- "Авторизация"
User -- "Просмотр открытых курсов"
User -- "Общение с пользователями через чат"
User -- "Редактирование данных своего профиля"

Student -- "Просмотр доступных курсов"
Student -- "Просмотр своих оценок"

Admin -- "Настройка доступа пользователей"
Admin -- "Просмотр оценок обучающихся"
Admin -- "Удаление чужих сообщений в чатах"
Admin -- "Редактирование данных чужого профиля"

Teacher -- "Просмотр\создание\удаление\изменение\n курса"
Teacher -- "Изменение\просмотр оценок проходящих курс обучающихся"
Teacher -- "Настройка доступа пользователей к своим курсам"

@enduml
