@startuml use_case
skinparam actorStyle awesome
left to right direction
actor Пользователь as User
actor Студент as Student
actor Преподаватель as Teacher
actor Администратор as Admin
actor Модератор as Moder
together{
  User <|- Student
  User <|- Teacher
  User <|- Admin
  User <|- Moder
}

rectangle "Образовательная платформа с онлайн-курсами" as Platform {
  together{
    usecase "Регистрация"
    usecase "Авторизация"
    usecase "Редактирование данных своего профиля"
    usecase "Просмотр открытых курсов"
    usecase "Общение с пользователями через чат"
  }
  together{
    usecase "Просмотр доступных курсов"
    usecase "Просмотр своих оценок"
  }
  usecase "Просмотр\создание\удаление\изменение\n своего курса"
  usecase "Просмотр\создание\удаление\изменение\n чужого курса"
  usecase "Изменение\просмотр оценок связанных студентов"
  usecase "Изменение\просмотр оценок студентов"
  usecase "Настройка ролей\доступа пользователей"
  usecase "Настройка доступа связанных студентов"
  usecase "Группировка связанных студентов"
  usecase "Группировка студентов"
  usecase "Редактирование данных чужого профиля"
  usecase "Изменение\удаление чужих сообщений в чатах"
  usecase "Написание своих сообщений"
  usecase "Редактирование своих сообщений"
  usecase "Удаление своих сообщений"
  usecase "Создание чатов"
  usecase "Удаление чатов"
}

"Общение с пользователями через чат" -- "Удаление чатов"
"Общение с пользователями через чат" -- "Редактирование своих сообщений"
"Общение с пользователями через чат" -- "Написание своих сообщений"
"Общение с пользователями через чат" -- "Удаление своих сообщений"
"Общение с пользователями через чат" -- "Создание чатов"

User -- "Регистрация"
User -- "Авторизация"
User -- "Просмотр открытых курсов"
User -- "Общение с пользователями через чат"
User -- "Редактирование данных своего профиля"

Student -- "Просмотр доступных курсов"
Student -- "Просмотр своих оценок"

Admin -- "Просмотр\создание\удаление\изменение\n чужого курса"
Admin -- "Настройка ролей\доступа пользователей"
Admin -- "Изменение\просмотр оценок студентов"
Admin -- "Группировка студентов"
Admin -- "Изменение\удаление чужих сообщений в чатах"
Admin -- "Редактирование данных чужого профиля"

Moder -- "Просмотр\создание\удаление\изменение\n чужого курса"
Moder -- "Изменение\удаление чужих сообщений в чатах"
Moder -- "Редактирование данных чужого профиля"

Teacher -- "Просмотр\создание\удаление\изменение\n своего курса"
Teacher -- "Настройка доступа связанных студентов"
Teacher -- "Группировка связанных студентов"
Teacher -- "Изменение\просмотр оценок связанных студентов"

@enduml