@startuml classDiagram
class User {
    +int ID
    +String username
    +String password
    +int RoleID
    +List<Chat> relatedChats
    +List<Course> availableCourses
    +List<Group> relatedGroups
    +registration()
    +authentication()
    +viewCourse()
}
class Group{
    +List<User> relatedUsers
    +User groupAdmin
}
class Chat{
    +int ID
    +List<User> users
}
class Message{
    +int ID
    +DateAndTime dateAndTime
    +String text
    +User sender
}
class Cours{
    +int ID
    +User creator
    +List<Student> students
}
class Grade {
    +int value
    +String description
    +Date date
}
class GradeList{

}
enum Permission{
    VIEWCOURCES
    EDITOWNCOURSE
    EDITOTHERCOURSE
    CHANGEPERMITIONS
    EDITGROUPS
    EDITOWNPROFILE
    EDITOTHERPROFILE
    EDITOWNCHATS
    EDITOTHERCHATS
    EDITOWNMESSAGES
    EDITOTHERMESSAGES
}
class Role{
    +List<Permission> permissions
}
User "*" -- "*" Cours : Имеет доступ
User "*" -- "*" Group : Состоит
    User "*" -- "*" Chat : Состоит
    Cours o-- GradeList
    GradeList *-- Grade
    User --> Role :"Имеет"
    Chat *-- "*" Message
    Role o-- Permission
    @enduml
