@startuml active
|Пользователь|
start
:Выбрать курс;
:Инициировать оплату курса;
|Система|
if () then ([Данный курс приобретен])
    |Система|
    :Вывести уведомление "Курс уже приобретен";
    :Открыть список курсов;
    stop 
else([Данный курс не приобретен])    
endif 
|Система|
:Открыть пользователю интерфейс оплаты курса;
fork
|Пользователь|
:Оплатить курс;
fork again
    |Система|
while ( ) is ([Оплата не прошла])
    :Ждать оплаты;
endwhile([Оплата прошла])
    end fork
fork
    :Предоставить пользователю доступ к курсу;
fork again
    if () then ([Есть общий чат для обучающихся курса])
        :Добавить пользователя в общий чат;
        if () then ([Есть автоматическое сообщение для новых участников])
            :Вывести автоматическое сообщение;
        endif
    else([Нет общего чата с обучающимися])
    endif
    end fork
:Открыть интерфейс курса;
stop
@enduml