@startuml diag
hide empty methods
skinparam Linetype ortho
abstract class Пользователь {
    + персональные_данные : String
    + логин : String
    + пароль : String
    + просмотреть_открытые_курсы() : void
    + общение_с_пользователями() : void
    + редактирование_профиля() : void
}


class Обучающийся {
    + просмотр_доступных_курсов() : void
    + просмотр_своих_оценок() : void
}

class Преподаватель {
    + создание_курса(Курс) : void
    + изменение_курса(Курс) : void
    + удаление_курса(Курс) : void
    + изменение_просмотр_оценок_обучающихся() : void
    + настройка_доступа_к_курсам() : void
}

class Администратор {
    + настройка_доступа_к_курсам()
    + удаление_чужих_сообщений()
    + редактирование_данных_чужого_профиля()
}

class Курс {
    + создать()
    + изменить()
    + удалить()
    + добавить_обучающегося()
    + удалить_обучающегося()
}
class Тема {
    + Название : String
    + Описание : String
    + создать()
    + изменить()
    + удалить()
}
class Урок {
    + текст урока : String
    + материалы : List<Файл>
    + создать()
    + изменить()
    + удалить()
}
class Тест {
    + название : String
    + создать()
    + изменить()
    + удалить()
}
abstract class Вопрос {
    + вопрос : String
    + создать()
    + изменить()
    + удалить()
}
class Вопрос_с_развернутым_ответом {
    + ответ : String
}
class Вопрос_с_одним_ответом {
    + варианты : List<String>
    + ответ : int
}
class Вопрос_с_несколькими_ответами {
    + варианты : List<String>
    + ответы : List<int>
}
class Оценка {
    + значение : int
    + комментарий : String
    + создать()
    + изменить()
    + удалить()
}
together{
    class Чат {
        + ID : int
        + название : String
        + текст_автоматического_сообщения : String
        + удалить_пользователя(Пользователь)
        + добавить_пользователя(Пользователь)
        + создать()
        + изменить()
        + удалить()
    }
    class Сообщение {
        + ID : int
        + текст : String
        + дата_отправки : Date
        + время_отправки : Time
        + создать()
        + изменить()
        + удалить()
    }
}

Чат o-left- "             *" Сообщение
Пользователь "*" -right- "*" Чат : использует
Пользователь "1" -- "*" Сообщение : использует

Курс "1" -- "             *" Оценка : сохраняется
Курс "*" -- "             *" Обучающийся : проходит
Оценка "*" -- "             1" Обучающийся : имеет
Курс "           *" -- "1" Преподаватель : управляет
Тема "*" --o Курс
Тема o-left- "*" Урок
Тема o-right- "*" Тест
Тест o-down- "*" Вопрос




Обучающийся --|> Пользователь
Преподаватель --|> Пользователь
Администратор --|> Пользователь

Вопрос_с_развернутым_ответом --|> Вопрос
Вопрос_с_одним_ответом --|> Вопрос
Вопрос_с_несколькими_ответами -left-|> Вопрос
@enduml
