@startuml diag
state "Запуск теста" as begining
state "Работа над вопросом" as work{
    state "Чтение вопроса" as readq
    state "Ответ на вопрос" as answerq
    [*] -right-> readq
    readq-right->answerq
    answerq-right->[*]
}
state "Отправка преподавателю" as send: do/ Отправка
state "Проверка преподавателем" as check : do/ Проверка
state "Выставление оценки" as makegrade : do/ Добавление оценки обучающегося
state "Для исправления" as forcorrection: exit/ Тест взят на исправление
[*] --> begining
begining -right-> work
work -->work:[Есть нерешенные вопросы]
work -down->send:[Все вопросы решены]
send-->check
check-->makegrade:[Оценка больше "3"]
check-->forcorrection:[Оценка меньше "3"]
forcorrection -->begining
makegrade --> [*]
@enduml