@startuml componentD
left to right direction
rectangle "Платформа с онлайн-курсами" as Platform {
  component "База данных пользователей" as UserDB
  component "Контроллер пользователей" as UserControl
  component "База данных курсов" as CourseDB
  component "Контроллер курсов" as CourseControl
  component "База данных Чатов" as ChatDB
  component "Контроллер чатов" as ChatControl
}
@enduml
' cloud NewsServer{
' component NewsDB
' component PublicationsDB
' component CategoryesDB
' component CommentsDB
' }
' cloud UserServer{
' component UsersDB
' component RolesDB
' }
' ()IMobileClient
' ()IWebClient
' ()IUsersEditor
' ()INewsEditor
' node webClient
' node Android
' node IOS
' NewsServer --- INewsEditor
' NewsServer --- INewsViewer
' UserServer --- IUsersEditor
' IUsersEditor <|-- IMobileClient
' INewsViewer <|-- IMobileClient
' IUsersEditor <|-- IWebClient
' INewsViewer <|-- IWebClient
' INewsEditor <|-- IWebClient
' IMobileClient <-- Android
' IMobileClient <-- IOS
' IWebClient <-- webClient
' CategoryesDB o-- PublicationsDB
' PublicationsDB *-- CommentsDB
' NewsDB o-- CategoryesDB
' UsersDB -down-> RolesDB
' @enduml
' !define skinparam backgroundColor #EEEBDC
' !define skinparam handwritten true