@startuml sostoianiy
'left to right direction
state Черновик: do / Редактирование
state Готов
state На_модерации: do / Рассмотрение
state Опубликовано
state На_доработке: do / Редактирование
state Архив
[*]-->Черновик
Черновик --> Готов:Работа закончена
Готов --> На_модерации:отправлен на модерацию
На_модерации --> Опубликовано: [Прошло проверку]
На_модерации --> На_доработке: [Не прошло проверку]
На_доработке -right-> На_модерации
Опубликовано -right-> [*]
Опубликовано --> Архив: Снято с публикации
Архив --> [*]
@enduml