@startuml componentD
left to right direction
rectangle "Платформа с онлайн-курсами" as Platform {
  database "База данных пользователей" as UserDB
  database "База данных курсов" as CourseDB
  database "База данных чатов" as ChatDB
  component "Пользовательский интерфейс" as UserInterface
  component "Контроллер пользователей" as UserControl
  component "Контроллер курсов" as CourseControl
  component "Контроллер чатов" as ChatControl
  component "API платформы" as API
  UserInterface-->API
  API-(0-UserControl
  API-(0-CourseControl
  API-(0-ChatControl
  UserControl .down. UserDB
  CourseControl .down. CourseDB
  ChatControl .down. ChatDB
}
@enduml