@startuml diag
node "Сервер курсов" as Server1 {
  component "Контроллер курсов"
  database "База данных курсов"
  "Контроллер курсов"-->"База данных курсов"
}
node "Сервер чатов" as Server2 {
  component "Контроллер чатов"
  database "База данных чатов"
  "Контроллер чатов"-->"База данных чатов"
}
node "Сервер польбзователей" as Server3 {
  component "Контроллер польбзователей"
  database "База данных польбзователей"
  "Контроллер польбзователей"-->"База данных польбзователей"
}
node "Сервер платформы" as Server4 {
  component "Пользовательский интерфейс"
  component "API платформы"
  "Пользовательский интерфейс"-right->"API платформы"
}
Server1 -up- Server4
Server2 -up- Server4
Server3 -up- Server4
node "Устройство администратора" as Device1
node "Устройство преподавателя" as Device2
node "Устройство обучающегося" as Device3
node "Компьютер системного администратора" as Device4
Server4 -up- Device1 : Глобальная сеть
Server4 -up- Device2 : Глобальная сеть
Server4 -up- Device3 : Глобальная сеть
Server4 -left- Device4 : Локальная сеть
@enduml